// Auto-curated component registry. Edit this file to change nav grouping.
export type ComponentEntry = {
  name: string
  slug: string
  description?: string
}

export type ComponentCategory = {
  title: string
  slug: string
  components: ComponentEntry[]
}

export const REGISTRY: ComponentCategory[] = [
  {
    title: 'Forms & Inputs',
    slug: 'forms',
    components: [
      { name: 'Button', slug: 'button', description: 'Clickable button with 24+ variants, sizes, icons, loading states' },
      { name: 'Input', slug: 'input', description: 'Text input with label, icons, error/helper states, edit tracking' },
      { name: 'Checkbox', slug: 'checkbox' },
      { name: 'CheckboxButton', slug: 'checkbox-button', description: 'Toggle button styled as checkbox' },
      { name: 'InputButton', slug: 'input-button', description: 'Inline input with label in bordered container' },
      { name: 'FilterPillButton', slug: 'filter-pill-button', description: 'Status filter pill with count badge' },
      { name: 'Switch', slug: 'switch' },
      { name: 'Textarea', slug: 'textarea' },
      { name: 'Label', slug: 'label' },
      { name: 'Dropdown', slug: 'dropdown', description: 'Searchable single/multi-select dropdown' },
      { name: 'UnifiedCurrencyDropdown', slug: 'unified-currency-dropdown', description: 'Currency picker with exchange rates' },
      { name: 'DatePicker', slug: 'date-picker', description: 'Calendar date picker with ranges' },
      { name: 'DateTimePicker', slug: 'date-time-picker', description: 'Date + time picker' },
      { name: 'FileAttachment', slug: 'file-attachment', description: 'File upload with previews' },
      { name: 'QuantityInputPopup', slug: 'quantity-input-popup', description: 'Quantity picker popup' },
      { name: 'FormToggle', slug: 'form-toggle', description: 'Toggle group switcher' },
    ],
  },
  {
    title: 'DataGrid',
    slug: 'datagrid',
    components: [
      { name: 'DataGrid', slug: 'data-grid', description: 'Advanced data table with 30+ features: virtualization, search, filter, sort, export, freeze, drag-drop' },
      { name: 'CardView', slug: 'card-view', description: 'Mobile-friendly card layout for DataGrid' },
      { name: 'DataVisualization', slug: 'data-visualization', description: 'Chart view for DataGrid' },
      { name: 'EditableCell', slug: 'editable-cell' },
      { name: 'EditableTextCell', slug: 'editable-text-cell' },
      { name: 'EditableDecimalCell', slug: 'editable-decimal-cell' },
      { name: 'EditableTableCell', slug: 'editable-table-cell' },
      { name: 'SelectionCell', slug: 'selection-cell' },
      { name: 'ActionsColumn', slug: 'actions-column' },
      { name: 'ActionsMenu', slug: 'actions-menu' },
      { name: 'PaginationControls', slug: 'pagination-controls' },
      { name: 'FilterBar', slug: 'filter-bar' },
      { name: 'AdvancedFilterModal', slug: 'advanced-filter-modal' },
      { name: 'ColumnChooserModal', slug: 'column-chooser-modal' },
      { name: 'SearchHighlighter', slug: 'search-highlighter' },
      { name: 'SearchNavigator', slug: 'search-navigator' },
    ],
  },
  {
    title: 'Modals & Dialogs',
    slug: 'modals',
    components: [
      { name: 'Modal', slug: 'modal', description: 'Base modal with size presets (sm, md, lg, xl, master, fullscreen)' },
      { name: 'StandardModal', slug: 'standard-modal' },
      { name: 'ModalAlert', slug: 'modal-alert', description: 'Alert dialog (confirm, info, warning, error)' },
      { name: 'Dialog', slug: 'dialog', description: 'Radix Dialog primitive' },
      { name: 'LogoutModal', slug: 'logout-modal' },
      { name: 'ImageModal', slug: 'image-modal' },
      { name: 'ThreeDModal', slug: 'three-d-modal' },
      { name: 'APIConfigModal', slug: 'api-config-modal' },
      { name: 'GlobalAPIConfigModal', slug: 'global-api-config-modal' },
      { name: 'SearchNewModal', slug: 'search-new-modal' },
    ],
  },
  {
    title: 'Layout',
    slug: 'layout',
    components: [
      { name: 'AppShell', slug: 'app-shell', description: 'App shell with sidebar + header + content' },
      { name: 'DynamicSidebar', slug: 'dynamic-sidebar', description: 'Collapsible sidebar with grouped nav' },
      { name: 'Footer', slug: 'footer' },
      { name: 'CompactFooter', slug: 'compact-footer' },
      { name: 'Page', slug: 'page' },
      { name: 'Grid', slug: 'grid', description: 'Responsive grid layout' },
      { name: 'HeaderSteps', slug: 'header-steps', description: 'Stepper UI in page header' },
      { name: 'FloatingActionButton', slug: 'floating-action-button', description: 'Mobile FAB' },
      { name: 'NavigationProgress', slug: 'navigation-progress' },
    ],
  },
  {
    title: 'Display & Feedback',
    slug: 'display',
    components: [
      { name: 'Card', slug: 'card', description: 'Container with header, content, footer' },
      { name: 'Alert', slug: 'alert' },
      { name: 'Badge', slug: 'badge' },
      { name: 'BooleanBadge', slug: 'boolean-badge' },
      { name: 'FilterBadge', slug: 'filter-badge' },
      { name: 'FilterBadgeGroup', slug: 'filter-badge-group' },
      { name: 'Tooltip', slug: 'tooltip' },
      { name: 'TooltipDetailed', slug: 'tooltip-detailed' },
      { name: 'Progress', slug: 'progress' },
      { name: 'Separator', slug: 'separator' },
      { name: 'Collapsible', slug: 'collapsible' },
      { name: 'Tabs', slug: 'tabs' },
      { name: 'Text', slug: 'text' },
      { name: 'Skeleton', slug: 'skeleton' },
      { name: 'SkeletonText', slug: 'skeleton-text' },
      { name: 'SkeletonTable', slug: 'skeleton-table' },
      { name: 'SkeletonFormFields', slug: 'skeleton-form-fields' },
      { name: 'Loading', slug: 'loading' },
      { name: 'LoadingOverlay', slug: 'loading-overlay' },
      { name: 'PageLoading', slug: 'page-loading' },
    ],
  },
  {
    title: 'Dashboard & Stats',
    slug: 'dashboard',
    components: [
      { name: 'StatsCard', slug: 'stats-card', description: 'KPI card with value, trend, icon' },
      { name: 'StatsGrid', slug: 'stats-grid' },
      { name: 'Kpi', slug: 'kpi' },
      { name: 'KpiTrend', slug: 'kpi-trend' },
      { name: 'KpiBeforeAfter', slug: 'kpi-before-after' },
      { name: 'KpiBreakdown', slug: 'kpi-breakdown' },
      { name: 'KpiComparison', slug: 'kpi-comparison' },
      { name: 'KpiRating', slug: 'kpi-rating' },
      { name: 'KpiScroll', slug: 'kpi-scroll' },
      { name: 'KpiQuickStats', slug: 'kpi-quick-stats' },
      { name: 'ChartCard', slug: 'chart-card' },
      { name: 'DashboardTooltip', slug: 'dashboard-tooltip' },
      { name: 'Sparkline', slug: 'sparkline' },
    ],
  },
  {
    title: 'Charts',
    slug: 'charts',
    components: [
      { name: 'LineChart', slug: 'line-chart' },
      { name: 'BarChart', slug: 'bar-chart' },
      { name: 'AreaChart', slug: 'area-chart' },
      { name: 'DonutChart', slug: 'donut-chart' },
      { name: 'ScatterChart', slug: 'scatter-chart' },
      { name: 'BubbleChart', slug: 'bubble-chart' },
      { name: 'RadarChart', slug: 'radar-chart' },
      { name: 'HeatmapChart', slug: 'heatmap-chart' },
      { name: 'TreemapChart', slug: 'treemap-chart' },
      { name: 'FunnelChart', slug: 'funnel-chart' },
      { name: 'GaugeChart', slug: 'gauge-chart' },
      { name: 'SankeyChart', slug: 'sankey-chart' },
      { name: 'BoxPlotChart', slug: 'box-plot-chart' },
      { name: 'BulletChart', slug: 'bullet-chart' },
      { name: 'WaterfallChart', slug: 'waterfall-chart' },
      { name: 'ParetoChart', slug: 'pareto-chart' },
      { name: 'GanttChart', slug: 'gantt-chart' },
      { name: 'HistogramChart', slug: 'histogram-chart' },
      { name: 'GeoMap', slug: 'geo-map' },
      { name: 'FlowMap', slug: 'flow-map' },
    ],
  },
  {
    title: 'Providers',
    slug: 'providers',
    components: [
      { name: 'ThemeProvider', slug: 'theme-provider' },
      { name: 'LanguageProvider', slug: 'language-provider' },
      { name: 'DeviceProvider', slug: 'device-provider' },
      { name: 'CurrencyProvider', slug: 'currency-provider' },
      { name: 'GlobalAlertProvider', slug: 'global-alert-provider' },
      { name: 'APIProvider', slug: 'api-provider' },
      { name: 'QueryProvider', slug: 'query-provider' },
      { name: 'AppConfigProvider', slug: 'app-config-provider' },
      { name: 'SearchPreferencesProvider', slug: 'search-preferences-provider' },
      { name: 'PageTitleProvider', slug: 'page-title-provider' },
      { name: 'AuthSessionProvider', slug: 'auth-session-provider' },
    ],
  },
  {
    title: 'Hooks',
    slug: 'hooks',
    components: [
      { name: 'useDevice', slug: 'use-device' },
      { name: 'useLanguage', slug: 'use-language' },
      { name: 'useCurrency', slug: 'use-currency' },
      { name: 'useGlobalAlert', slug: 'use-global-alert' },
      { name: 'useQuickAlert', slug: 'use-quick-alert' },
      { name: 'useModalAlert', slug: 'use-modal-alert' },
      { name: 'useAPI', slug: 'use-api' },
      { name: 'useAppConfig', slug: 'use-app-config' },
      { name: 'usePageTitle', slug: 'use-page-title' },
      { name: 'useSearchPreferences', slug: 'use-search-preferences' },
      { name: 'useClipboard', slug: 'use-clipboard' },
      { name: 'useDataGridState', slug: 'use-data-grid-state' },
      { name: 'useCellEditing', slug: 'use-cell-editing' },
      { name: 'useCellRangeSelection', slug: 'use-cell-range-selection' },
      { name: 'useKeyboardNavigation', slug: 'use-keyboard-navigation' },
      { name: 'useSearchNavigation', slug: 'use-search-navigation' },
    ],
  },
  {
    title: 'Utilities',
    slug: 'utils',
    components: [
      { name: 'cn', slug: 'cn', description: 'clsx + tailwind-merge helper' },
      { name: 'exportToCSV', slug: 'export-to-csv' },
      { name: 'exportToExcel', slug: 'export-to-excel' },
      { name: 'exportToJSON', slug: 'export-to-json' },
      { name: 'exportToPDF', slug: 'export-to-pdf' },
      { name: 'exportData', slug: 'export-data' },
      { name: 'importFromCSV', slug: 'import-from-csv' },
      { name: 'importFromExcel', slug: 'import-from-excel' },
      { name: 'importFromJSON', slug: 'import-from-json' },
      { name: 'importData', slug: 'import-data' },
      { name: 'fuzzyMatch', slug: 'fuzzy-match' },
      { name: 'advancedSearch', slug: 'advanced-search' },
      { name: 'createActionsColumn', slug: 'create-actions-column' },
      { name: 'createSelectColumn', slug: 'create-select-column' },
    ],
  },
]

// Hand-crafted pages — auto-gen will skip these
export const HAND_CRAFTED = new Set([
  'data-grid',
  'modal',
  'date-picker',
  'dropdown',
  'dynamic-sidebar',
  'button',
  'input',
  'card',
])
