#!/usr/bin/env node
// Regenerates src/lib/icons.ts from every `from '@/lib/icons'` import in src. Run after adding icons.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import path from 'node:path'
const root = path.resolve(import.meta.dirname, '..')
const files = []
;(function walk(d) { for (const e of readdirSync(d)) { const f = path.join(d, e); if (statSync(f).isDirectory()) walk(f); else if (/\.(ts|tsx)$/.test(e) && !f.endsWith('.d.ts') && !f.endsWith('icons.ts')) files.push(f) } })(path.join(root, 'src'))
const names = new Set()
for (const f of files) for (const m of readFileSync(f, 'utf8').matchAll(/import\s+\{([^}]+)\}\s+from\s+['"]@\/lib\/icons['"]/g))
  for (let p of m[1].split(',')) { p = p.trim().replace(/^type\s+/, ''); if (p && !/^Lucide(Icon|Props)$/.test(p)) names.add(p.split(/\s+as\s+/)[0].trim()) }
const kebab = (n) => n.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/([A-Z])([A-Z][a-z])/g, '$1-$2').replace(/([a-zA-Z])([0-9])/g, '$1-$2').toLowerCase()
const file = (n) => (n === 'FileIcon' ? 'file' : kebab(n))
const sorted = [...names].sort()
let out = '// Generated by scripts/gen-icons.mjs. Icons are imported by deep path so that host bundlers\n// only ship the icons actually used; a barrel import of lucide-react from inside node_modules\n// would drag in the whole icon set. Re-run the generator when adding icons.\nimport type { LucideIcon } from "lucide-react"\n\n'
for (const n of sorted) out += `import _${n} from "lucide-react/dist/esm/icons/${file(n)}"\n`
out += '\nexport type { LucideIcon, LucideProps } from "lucide-react"\n\n'
for (const n of sorted) out += `export const ${n}: LucideIcon = _${n}\n`
writeFileSync(path.join(root, 'src/lib/icons.ts'), out)
console.log(`icons.ts regenerated with ${sorted.length} icons`)
