/**
 * Approval Workflow Types
 *
 * Types for multi-level approval workflows and escalations.
 * Supports quotation approvals, master data changes, and other approval processes.
 */

/**
 * Approval status
 */
export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ESCALATED = 'ESCALATED',
  WITHDRAWN = 'WITHDRAWN',
  EXPIRED = 'EXPIRED'
}

/**
 * Approval workflow entry
 */
export interface ApprovalWorkflow {
  /** Approval ID (generated by backend) */
  approvalId?: number

  /** Entity type being approved (e.g., 'Quotation', 'Process', 'Machine') */
  entityType: string

  /** Entity ID */
  entityId: number

  /** User who requested approval */
  requestedBy: number
  requestedByName?: string

  /** Current approval level (1, 2, 3, etc.) */
  approvalLevel: number

  /** User who needs to approve (current level) */
  approverId?: number
  approverName?: string

  /** Current status */
  status: ApprovalStatus

  /** Comments/reason for approval/rejection */
  comments?: string

  /** When approval was requested */
  requestedAt: Date | string

  /** When approval was responded to */
  respondedAt?: Date | string

  /** Metadata (entity details, amount, etc.) */
  metadata?: Record<string, any>
}

/**
 * Approval chain (history of all approval levels)
 */
export interface ApprovalChain {
  /** Entity details */
  entityType: string
  entityId: number

  /** Current overall status */
  overallStatus: ApprovalStatus

  /** All approval levels */
  levels: ApprovalWorkflow[]

  /** Total number of levels required */
  totalLevels: number

  /** Current level being processed */
  currentLevel: number

  /** Whether approval is complete */
  isComplete: boolean

  /** Final outcome */
  finalOutcome?: 'approved' | 'rejected' | 'withdrawn'
}

/**
 * Approval configuration (per entity type)
 */
export interface ApprovalConfig {
  /** Entity type */
  entityType: string

  /** Is approval required for this entity type */
  approvalRequired: boolean

  /** Number of approval levels */
  approvalLevels: number

  /** Threshold rules (e.g., amount > 50000 requires approval) */
  thresholds?: Array<{
    field: string
    operator: '>' | '<' | '=' | '>=' | '<='
    value: number
    requiresApproval: boolean
  }>

  /** Auto-assign approvers by level */
  autoAssignApprovers?: {
    level1?: number[] // User IDs
    level2?: number[]
    level3?: number[]
  }

  /** Timeout settings */
  timeoutDays?: number // Approval expires after X days

  /** Can requester withdraw */
  allowWithdrawal: boolean

  /** Can requester escalate */
  allowEscalation: boolean
}

/**
 * Request approval
 */
export interface RequestApprovalRequest {
  EntityType: string
  EntityID: number
  Comments?: string
  Metadata?: Record<string, any>
}

/**
 * Response from requesting approval
 */
export interface RequestApprovalResponse {
  success: boolean
  data?: {
    approvalId: number
    approvalLevel: number
    approverId?: number
    requestedAt: string
  }
  error?: string
  details?: string
}

/**
 * Approve/Reject request
 */
export interface ProcessApprovalRequest {
  ApprovalID: number
  Action: 'APPROVE' | 'REJECT'
  Comments?: string
}

/**
 * Response from processing approval
 */
export interface ProcessApprovalResponse {
  success: boolean
  data?: {
    approvalId: number
    status: ApprovalStatus
    nextLevel?: number
    nextApproverId?: number
    isComplete: boolean
  }
  error?: string
  details?: string
}

/**
 * Escalate approval request
 */
export interface EscalateApprovalRequest {
  ApprovalID: number
  ToUserID: number
  Reason: string
}

/**
 * Response from escalating approval
 */
export interface EscalateApprovalResponse {
  success: boolean
  data?: {
    approvalId: number
    newApproverId: number
    escalatedAt: string
  }
  error?: string
  details?: string
}

/**
 * Get pending approvals response
 */
export interface PendingApprovalsResponse {
  success: boolean
  data?: ApprovalWorkflow[]
  error?: string
  details?: string
}

/**
 * Get approval chain response
 */
export interface ApprovalChainResponse {
  success: boolean
  data?: ApprovalChain
  error?: string
  details?: string
}

/**
 * Approval notification
 * Used for real-time notifications when approval status changes
 */
export interface ApprovalNotification {
  /** Notification ID */
  notificationId: number

  /** User to notify */
  userId: number

  /** Approval ID */
  approvalId: number

  /** Notification type */
  type: 'approval_requested' | 'approval_approved' | 'approval_rejected' | 'approval_escalated'

  /** Notification message */
  message: string

  /** Is read */
  isRead: boolean

  /** Created at */
  createdAt: Date | string
}
