/**
 * Draft System Types
 *
 * Types for auto-saving estimation work-in-progress and managing drafts.
 * Drafts are stored securely in SQL database via C# backend (NO localStorage for sensitive data).
 *
 * Security: All draft data stored in backend database, not client-side storage.
 */

/**
 * Draft entry
 */
export interface Draft {
  /** Draft ID (generated by backend) */
  draftId?: number

  /** User who owns this draft */
  userId: number

  /** Company context */
  companyId: number

  /** Module (e.g., 'ESTIMATION', 'QUOTATION') */
  module: string

  /** Human-readable draft name */
  draftName: string

  /** Full state data (JSON) - entire estimation state */
  draftData: any

  /** Whether this is an auto-save draft */
  isAutoSave: boolean

  /** Last saved timestamp */
  lastSaved: Date | string

  /** Expiration date (auto-cleanup) */
  expiresAt: Date | string

  /** Creation timestamp */
  createdAt?: Date | string
}

/**
 * Draft metadata (for listing drafts without full data)
 */
export interface DraftMetadata {
  /** Draft ID */
  draftId: number

  /** Draft name */
  draftName: string

  /** Module */
  module: string

  /** Is auto-save draft */
  isAutoSave: boolean

  /** Last saved timestamp */
  lastSaved: Date | string

  /** Expiration date */
  expiresAt: Date | string

  /** Preview data (extracted from draftData for quick display) */
  previewData?: {
    jobName?: string
    clientName?: string
    totalCost?: number
    quoteNumber?: string
    category?: string
    [key: string]: any
  }
}

/**
 * Request for saving a draft
 */
export interface SaveDraftRequest {
  DraftName: string
  Module: string
  DraftData: any // Will be JSON stringified
  IsAutoSave: boolean
}

/**
 * Response from saving a draft
 */
export interface SaveDraftResponse {
  success: boolean
  data?: {
    draftId: number
    lastSaved: string
  }
  error?: string
  details?: string
}

/**
 * Response from loading a draft
 */
export interface LoadDraftResponse {
  success: boolean
  data?: Draft
  error?: string
  details?: string
}

/**
 * Response from listing drafts
 */
export interface ListDraftsResponse {
  success: boolean
  data?: DraftMetadata[]
  error?: string
  details?: string
}

/**
 * Response from deleting a draft
 */
export interface DeleteDraftResponse {
  success: boolean
  message?: string
  error?: string
  details?: string
}

/**
 * Draft settings (user preferences)
 */
export interface DraftSettings {
  /** Enable/disable auto-save */
  autoSaveEnabled: boolean

  /** Auto-save interval in seconds */
  autoSaveInterval: number

  /** Draft retention period in days */
  draftRetentionDays: number

  /** Show expiry warnings */
  showExpiryWarnings: boolean

  /** Warn X days before expiry */
  expiryWarningDays: number
}

/**
 * Default draft settings
 */
export const DEFAULT_DRAFT_SETTINGS: DraftSettings = {
  autoSaveEnabled: true,
  autoSaveInterval: 30, // 30 seconds
  draftRetentionDays: 30, // 30 days
  showExpiryWarnings: true,
  expiryWarningDays: 3 // Warn 3 days before expiry
}

/**
 * Draft conflict information
 * Used when detecting if draft is outdated or conflicting
 */
export interface DraftConflict {
  /** Is there a conflict */
  hasConflict: boolean

  /** Conflict reason */
  reason?: 'draft_older' | 'simultaneous_edit' | 'entity_deleted'

  /** Current version timestamp */
  currentVersion?: Date | string

  /** Draft version timestamp */
  draftVersion?: Date | string

  /** Conflict details */
  details?: string
}
