// Generated by scripts/gen-icons.mjs. Icons are imported by deep path so that host bundlers
// only ship the icons actually used; a barrel import of lucide-react from inside node_modules
// would drag in the whole icon set. Re-run the generator when adding icons.
import type { LucideIcon } from "lucide-react"

import _Activity from "lucide-react/dist/esm/icons/activity"
import _AlertCircle from "lucide-react/dist/esm/icons/alert-circle"
import _AlertOctagon from "lucide-react/dist/esm/icons/alert-octagon"
import _AlertTriangle from "lucide-react/dist/esm/icons/alert-triangle"
import _Archive from "lucide-react/dist/esm/icons/archive"
import _ArrowDown from "lucide-react/dist/esm/icons/arrow-down"
import _ArrowLeft from "lucide-react/dist/esm/icons/arrow-left"
import _ArrowRight from "lucide-react/dist/esm/icons/arrow-right"
import _ArrowUp from "lucide-react/dist/esm/icons/arrow-up"
import _ArrowUpDown from "lucide-react/dist/esm/icons/arrow-up-down"
import _Ban from "lucide-react/dist/esm/icons/ban"
import _BarChart3 from "lucide-react/dist/esm/icons/bar-chart-3"
import _Bell from "lucide-react/dist/esm/icons/bell"
import _BellRing from "lucide-react/dist/esm/icons/bell-ring"
import _BookOpen from "lucide-react/dist/esm/icons/book-open"
import _Bot from "lucide-react/dist/esm/icons/bot"
import _Box from "lucide-react/dist/esm/icons/box"
import _Boxes from "lucide-react/dist/esm/icons/boxes"
import _Briefcase from "lucide-react/dist/esm/icons/briefcase"
import _Building from "lucide-react/dist/esm/icons/building"
import _Building2 from "lucide-react/dist/esm/icons/building-2"
import _Calculator from "lucide-react/dist/esm/icons/calculator"
import _Calendar from "lucide-react/dist/esm/icons/calendar"
import _CalendarDays from "lucide-react/dist/esm/icons/calendar-days"
import _Camera from "lucide-react/dist/esm/icons/camera"
import _Check from "lucide-react/dist/esm/icons/check"
import _CheckCheck from "lucide-react/dist/esm/icons/check-check"
import _CheckCircle from "lucide-react/dist/esm/icons/check-circle"
import _ChevronDown from "lucide-react/dist/esm/icons/chevron-down"
import _ChevronLeft from "lucide-react/dist/esm/icons/chevron-left"
import _ChevronRight from "lucide-react/dist/esm/icons/chevron-right"
import _ChevronUp from "lucide-react/dist/esm/icons/chevron-up"
import _ChevronsDownUp from "lucide-react/dist/esm/icons/chevrons-down-up"
import _ChevronsLeft from "lucide-react/dist/esm/icons/chevrons-left"
import _ChevronsRight from "lucide-react/dist/esm/icons/chevrons-right"
import _ChevronsUpDown from "lucide-react/dist/esm/icons/chevrons-up-down"
import _Circle from "lucide-react/dist/esm/icons/circle"
import _CircleUser from "lucide-react/dist/esm/icons/circle-user"
import _ClipboardCheck from "lucide-react/dist/esm/icons/clipboard-check"
import _ClipboardList from "lucide-react/dist/esm/icons/clipboard-list"
import _Clock from "lucide-react/dist/esm/icons/clock"
import _Cog from "lucide-react/dist/esm/icons/cog"
import _Columns3 from "lucide-react/dist/esm/icons/columns-3"
import _Copy from "lucide-react/dist/esm/icons/copy"
import _Database from "lucide-react/dist/esm/icons/database"
import _DollarSign from "lucide-react/dist/esm/icons/dollar-sign"
import _Download from "lucide-react/dist/esm/icons/download"
import _Edit from "lucide-react/dist/esm/icons/edit"
import _ExternalLink from "lucide-react/dist/esm/icons/external-link"
import _Eye from "lucide-react/dist/esm/icons/eye"
import _EyeOff from "lucide-react/dist/esm/icons/eye-off"
import _Factory from "lucide-react/dist/esm/icons/factory"
import _File from "lucide-react/dist/esm/icons/file"
import _FileArchive from "lucide-react/dist/esm/icons/file-archive"
import _FileAudio from "lucide-react/dist/esm/icons/file-audio"
import _FileBarChart from "lucide-react/dist/esm/icons/file-bar-chart"
import _FileCheck from "lucide-react/dist/esm/icons/file-check"
import _FileIcon from "lucide-react/dist/esm/icons/file"
import _FileImage from "lucide-react/dist/esm/icons/file-image"
import _FileJson from "lucide-react/dist/esm/icons/file-json"
import _FileOutput from "lucide-react/dist/esm/icons/file-output"
import _FileSpreadsheet from "lucide-react/dist/esm/icons/file-spreadsheet"
import _FileText from "lucide-react/dist/esm/icons/file-text"
import _FileVideo from "lucide-react/dist/esm/icons/file-video"
import _Files from "lucide-react/dist/esm/icons/files"
import _Filter from "lucide-react/dist/esm/icons/filter"
import _Gauge from "lucide-react/dist/esm/icons/gauge"
import _Grid3X3 from "lucide-react/dist/esm/icons/grid-3-x-3"
import _GripVertical from "lucide-react/dist/esm/icons/grip-vertical"
import _Hash from "lucide-react/dist/esm/icons/hash"
import _HelpCircle from "lucide-react/dist/esm/icons/help-circle"
import _History from "lucide-react/dist/esm/icons/history"
import _Home from "lucide-react/dist/esm/icons/home"
import _Image from "lucide-react/dist/esm/icons/image"
import _Info from "lucide-react/dist/esm/icons/info"
import _Layers from "lucide-react/dist/esm/icons/layers"
import _LayoutGrid from "lucide-react/dist/esm/icons/layout-grid"
import _Lightbulb from "lucide-react/dist/esm/icons/lightbulb"
import _LineChart from "lucide-react/dist/esm/icons/line-chart"
import _ListFilter from "lucide-react/dist/esm/icons/list-filter"
import _Loader2 from "lucide-react/dist/esm/icons/loader-2"
import _Lock from "lucide-react/dist/esm/icons/lock"
import _LogOut from "lucide-react/dist/esm/icons/log-out"
import _Mail from "lucide-react/dist/esm/icons/mail"
import _Maximize from "lucide-react/dist/esm/icons/maximize"
import _Maximize2 from "lucide-react/dist/esm/icons/maximize-2"
import _Menu from "lucide-react/dist/esm/icons/menu"
import _MessageSquare from "lucide-react/dist/esm/icons/message-square"
import _Mic from "lucide-react/dist/esm/icons/mic"
import _MicOff from "lucide-react/dist/esm/icons/mic-off"
import _Minus from "lucide-react/dist/esm/icons/minus"
import _Monitor from "lucide-react/dist/esm/icons/monitor"
import _Moon from "lucide-react/dist/esm/icons/moon"
import _MoreHorizontal from "lucide-react/dist/esm/icons/more-horizontal"
import _MoreVertical from "lucide-react/dist/esm/icons/more-vertical"
import _Move from "lucide-react/dist/esm/icons/move"
import _Package from "lucide-react/dist/esm/icons/package"
import _Palette from "lucide-react/dist/esm/icons/palette"
import _PanelLeftClose from "lucide-react/dist/esm/icons/panel-left-close"
import _PanelLeftOpen from "lucide-react/dist/esm/icons/panel-left-open"
import _Paperclip from "lucide-react/dist/esm/icons/paperclip"
import _Pencil from "lucide-react/dist/esm/icons/pencil"
import _Phone from "lucide-react/dist/esm/icons/phone"
import _PieChart from "lucide-react/dist/esm/icons/pie-chart"
import _Pin from "lucide-react/dist/esm/icons/pin"
import _PinOff from "lucide-react/dist/esm/icons/pin-off"
import _Plus from "lucide-react/dist/esm/icons/plus"
import _Printer from "lucide-react/dist/esm/icons/printer"
import _Receipt from "lucide-react/dist/esm/icons/receipt"
import _RefreshCw from "lucide-react/dist/esm/icons/refresh-cw"
import _Reply from "lucide-react/dist/esm/icons/reply"
import _RotateCcw from "lucide-react/dist/esm/icons/rotate-ccw"
import _RotateCw from "lucide-react/dist/esm/icons/rotate-cw"
import _Save from "lucide-react/dist/esm/icons/save"
import _Search from "lucide-react/dist/esm/icons/search"
import _Send from "lucide-react/dist/esm/icons/send"
import _Server from "lucide-react/dist/esm/icons/server"
import _Settings from "lucide-react/dist/esm/icons/settings"
import _Settings2 from "lucide-react/dist/esm/icons/settings-2"
import _Share2 from "lucide-react/dist/esm/icons/share-2"
import _Shield from "lucide-react/dist/esm/icons/shield"
import _ShieldAlert from "lucide-react/dist/esm/icons/shield-alert"
import _ShoppingCart from "lucide-react/dist/esm/icons/shopping-cart"
import _Sidebar from "lucide-react/dist/esm/icons/sidebar"
import _Smartphone from "lucide-react/dist/esm/icons/smartphone"
import _Smile from "lucide-react/dist/esm/icons/smile"
import _SortAsc from "lucide-react/dist/esm/icons/sort-asc"
import _SortDesc from "lucide-react/dist/esm/icons/sort-desc"
import _Sparkles from "lucide-react/dist/esm/icons/sparkles"
import _Star from "lucide-react/dist/esm/icons/star"
import _StarOff from "lucide-react/dist/esm/icons/star-off"
import _Sun from "lucide-react/dist/esm/icons/sun"
import _Tablet from "lucide-react/dist/esm/icons/tablet"
import _Tag from "lucide-react/dist/esm/icons/tag"
import _Target from "lucide-react/dist/esm/icons/target"
import _TestTube from "lucide-react/dist/esm/icons/test-tube"
import _ThumbsDown from "lucide-react/dist/esm/icons/thumbs-down"
import _ThumbsUp from "lucide-react/dist/esm/icons/thumbs-up"
import _ToggleLeft from "lucide-react/dist/esm/icons/toggle-left"
import _Trash2 from "lucide-react/dist/esm/icons/trash-2"
import _TrendingDown from "lucide-react/dist/esm/icons/trending-down"
import _TrendingUp from "lucide-react/dist/esm/icons/trending-up"
import _Type from "lucide-react/dist/esm/icons/type"
import _Upload from "lucide-react/dist/esm/icons/upload"
import _User from "lucide-react/dist/esm/icons/user"
import _UserCog from "lucide-react/dist/esm/icons/user-cog"
import _UserPlus from "lucide-react/dist/esm/icons/user-plus"
import _Users from "lucide-react/dist/esm/icons/users"
import _Video from "lucide-react/dist/esm/icons/video"
import _Volume2 from "lucide-react/dist/esm/icons/volume-2"
import _VolumeX from "lucide-react/dist/esm/icons/volume-x"
import _WifiOff from "lucide-react/dist/esm/icons/wifi-off"
import _Wrench from "lucide-react/dist/esm/icons/wrench"
import _X from "lucide-react/dist/esm/icons/x"
import _XCircle from "lucide-react/dist/esm/icons/x-circle"
import _Zap from "lucide-react/dist/esm/icons/zap"

export type { LucideIcon, LucideProps } from "lucide-react"

export const Activity: LucideIcon = _Activity
export const AlertCircle: LucideIcon = _AlertCircle
export const AlertOctagon: LucideIcon = _AlertOctagon
export const AlertTriangle: LucideIcon = _AlertTriangle
export const Archive: LucideIcon = _Archive
export const ArrowDown: LucideIcon = _ArrowDown
export const ArrowLeft: LucideIcon = _ArrowLeft
export const ArrowRight: LucideIcon = _ArrowRight
export const ArrowUp: LucideIcon = _ArrowUp
export const ArrowUpDown: LucideIcon = _ArrowUpDown
export const Ban: LucideIcon = _Ban
export const BarChart3: LucideIcon = _BarChart3
export const Bell: LucideIcon = _Bell
export const BellRing: LucideIcon = _BellRing
export const BookOpen: LucideIcon = _BookOpen
export const Bot: LucideIcon = _Bot
export const Box: LucideIcon = _Box
export const Boxes: LucideIcon = _Boxes
export const Briefcase: LucideIcon = _Briefcase
export const Building: LucideIcon = _Building
export const Building2: LucideIcon = _Building2
export const Calculator: LucideIcon = _Calculator
export const Calendar: LucideIcon = _Calendar
export const CalendarDays: LucideIcon = _CalendarDays
export const Camera: LucideIcon = _Camera
export const Check: LucideIcon = _Check
export const CheckCheck: LucideIcon = _CheckCheck
export const CheckCircle: LucideIcon = _CheckCircle
export const ChevronDown: LucideIcon = _ChevronDown
export const ChevronLeft: LucideIcon = _ChevronLeft
export const ChevronRight: LucideIcon = _ChevronRight
export const ChevronUp: LucideIcon = _ChevronUp
export const ChevronsDownUp: LucideIcon = _ChevronsDownUp
export const ChevronsLeft: LucideIcon = _ChevronsLeft
export const ChevronsRight: LucideIcon = _ChevronsRight
export const ChevronsUpDown: LucideIcon = _ChevronsUpDown
export const Circle: LucideIcon = _Circle
export const CircleUser: LucideIcon = _CircleUser
export const ClipboardCheck: LucideIcon = _ClipboardCheck
export const ClipboardList: LucideIcon = _ClipboardList
export const Clock: LucideIcon = _Clock
export const Cog: LucideIcon = _Cog
export const Columns3: LucideIcon = _Columns3
export const Copy: LucideIcon = _Copy
export const Database: LucideIcon = _Database
export const DollarSign: LucideIcon = _DollarSign
export const Download: LucideIcon = _Download
export const Edit: LucideIcon = _Edit
export const ExternalLink: LucideIcon = _ExternalLink
export const Eye: LucideIcon = _Eye
export const EyeOff: LucideIcon = _EyeOff
export const Factory: LucideIcon = _Factory
export const File: LucideIcon = _File
export const FileArchive: LucideIcon = _FileArchive
export const FileAudio: LucideIcon = _FileAudio
export const FileBarChart: LucideIcon = _FileBarChart
export const FileCheck: LucideIcon = _FileCheck
export const FileIcon: LucideIcon = _FileIcon
export const FileImage: LucideIcon = _FileImage
export const FileJson: LucideIcon = _FileJson
export const FileOutput: LucideIcon = _FileOutput
export const FileSpreadsheet: LucideIcon = _FileSpreadsheet
export const FileText: LucideIcon = _FileText
export const FileVideo: LucideIcon = _FileVideo
export const Files: LucideIcon = _Files
export const Filter: LucideIcon = _Filter
export const Gauge: LucideIcon = _Gauge
export const Grid3X3: LucideIcon = _Grid3X3
export const GripVertical: LucideIcon = _GripVertical
export const Hash: LucideIcon = _Hash
export const HelpCircle: LucideIcon = _HelpCircle
export const History: LucideIcon = _History
export const Home: LucideIcon = _Home
export const Image: LucideIcon = _Image
export const Info: LucideIcon = _Info
export const Layers: LucideIcon = _Layers
export const LayoutGrid: LucideIcon = _LayoutGrid
export const Lightbulb: LucideIcon = _Lightbulb
export const LineChart: LucideIcon = _LineChart
export const ListFilter: LucideIcon = _ListFilter
export const Loader2: LucideIcon = _Loader2
export const Lock: LucideIcon = _Lock
export const LogOut: LucideIcon = _LogOut
export const Mail: LucideIcon = _Mail
export const Maximize: LucideIcon = _Maximize
export const Maximize2: LucideIcon = _Maximize2
export const Menu: LucideIcon = _Menu
export const MessageSquare: LucideIcon = _MessageSquare
export const Mic: LucideIcon = _Mic
export const MicOff: LucideIcon = _MicOff
export const Minus: LucideIcon = _Minus
export const Monitor: LucideIcon = _Monitor
export const Moon: LucideIcon = _Moon
export const MoreHorizontal: LucideIcon = _MoreHorizontal
export const MoreVertical: LucideIcon = _MoreVertical
export const Move: LucideIcon = _Move
export const Package: LucideIcon = _Package
export const Palette: LucideIcon = _Palette
export const PanelLeftClose: LucideIcon = _PanelLeftClose
export const PanelLeftOpen: LucideIcon = _PanelLeftOpen
export const Paperclip: LucideIcon = _Paperclip
export const Pencil: LucideIcon = _Pencil
export const Phone: LucideIcon = _Phone
export const PieChart: LucideIcon = _PieChart
export const Pin: LucideIcon = _Pin
export const PinOff: LucideIcon = _PinOff
export const Plus: LucideIcon = _Plus
export const Printer: LucideIcon = _Printer
export const Receipt: LucideIcon = _Receipt
export const RefreshCw: LucideIcon = _RefreshCw
export const Reply: LucideIcon = _Reply
export const RotateCcw: LucideIcon = _RotateCcw
export const RotateCw: LucideIcon = _RotateCw
export const Save: LucideIcon = _Save
export const Search: LucideIcon = _Search
export const Send: LucideIcon = _Send
export const Server: LucideIcon = _Server
export const Settings: LucideIcon = _Settings
export const Settings2: LucideIcon = _Settings2
export const Share2: LucideIcon = _Share2
export const Shield: LucideIcon = _Shield
export const ShieldAlert: LucideIcon = _ShieldAlert
export const ShoppingCart: LucideIcon = _ShoppingCart
export const Sidebar: LucideIcon = _Sidebar
export const Smartphone: LucideIcon = _Smartphone
export const Smile: LucideIcon = _Smile
export const SortAsc: LucideIcon = _SortAsc
export const SortDesc: LucideIcon = _SortDesc
export const Sparkles: LucideIcon = _Sparkles
export const Star: LucideIcon = _Star
export const StarOff: LucideIcon = _StarOff
export const Sun: LucideIcon = _Sun
export const Tablet: LucideIcon = _Tablet
export const Tag: LucideIcon = _Tag
export const Target: LucideIcon = _Target
export const TestTube: LucideIcon = _TestTube
export const ThumbsDown: LucideIcon = _ThumbsDown
export const ThumbsUp: LucideIcon = _ThumbsUp
export const ToggleLeft: LucideIcon = _ToggleLeft
export const Trash2: LucideIcon = _Trash2
export const TrendingDown: LucideIcon = _TrendingDown
export const TrendingUp: LucideIcon = _TrendingUp
export const Type: LucideIcon = _Type
export const Upload: LucideIcon = _Upload
export const User: LucideIcon = _User
export const UserCog: LucideIcon = _UserCog
export const UserPlus: LucideIcon = _UserPlus
export const Users: LucideIcon = _Users
export const Video: LucideIcon = _Video
export const Volume2: LucideIcon = _Volume2
export const VolumeX: LucideIcon = _VolumeX
export const WifiOff: LucideIcon = _WifiOff
export const Wrench: LucideIcon = _Wrench
export const X: LucideIcon = _X
export const XCircle: LucideIcon = _XCircle
export const Zap: LucideIcon = _Zap
